### PR TITLE
Cleaning path and Case Matching of Controller

### PR DESCRIPTION
**Pull request by geetanshu-m**
### Summary 

- Patch for potential errors.

### Testing Instructions

- In media-manager upload any image.
- Go to edit option of that image, goto Smart Crop tab, Select the focus area, save and close the editor.
- Now add that image to the article and see If the image changes when the browser window width is changed.

### CODE REVIEW

**Comment by kasvith** [comment]
is there any problem in upstream? because i get this error

image

**Review by kasvith — APPROVED** [review]
seems fine

**Comment by geetanshu-m** [comment]
@kasvith Yes, seems like this is an upstream problem, cause we haven't dealt with the ```Login``` module

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/issues/20902

**Pull request merged**
